// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "alamat", Type: field.TypeString},
		{Name: "telepon", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "image", Type: field.TypeString},
		{Name: "qty", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// ProductKeluarsColumns holds the columns for the "product_keluars" table.
	ProductKeluarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "qty", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductKeluarsTable holds the schema information for the "product_keluars" table.
	ProductKeluarsTable = &schema.Table{
		Name:       "product_keluars",
		Columns:    ProductKeluarsColumns,
		PrimaryKey: []*schema.Column{ProductKeluarsColumns[0]},
	}
	// ProductMasuksColumns holds the columns for the "product_masuks" table.
	ProductMasuksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "qty", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProductMasuksTable holds the schema information for the "product_masuks" table.
	ProductMasuksTable = &schema.Table{
		Name:       "product_masuks",
		Columns:    ProductMasuksColumns,
		PrimaryKey: []*schema.Column{ProductMasuksColumns[0]},
	}
	// SuppliersColumns holds the columns for the "suppliers" table.
	SuppliersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "alamat", Type: field.TypeString},
		{Name: "telepon", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SuppliersTable holds the schema information for the "suppliers" table.
	SuppliersTable = &schema.Table{
		Name:       "suppliers",
		Columns:    SuppliersColumns,
		PrimaryKey: []*schema.Column{SuppliersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "firstname", Type: field.TypeString},
		{Name: "lastname", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// CategoryProductkeluarColumns holds the columns for the "category_productkeluar" table.
	CategoryProductkeluarColumns = []*schema.Column{
		{Name: "category_id", Type: field.TypeInt},
		{Name: "product_keluar_id", Type: field.TypeInt},
	}
	// CategoryProductkeluarTable holds the schema information for the "category_productkeluar" table.
	CategoryProductkeluarTable = &schema.Table{
		Name:       "category_productkeluar",
		Columns:    CategoryProductkeluarColumns,
		PrimaryKey: []*schema.Column{CategoryProductkeluarColumns[0], CategoryProductkeluarColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "category_productkeluar_category_id",
				Columns:    []*schema.Column{CategoryProductkeluarColumns[0]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "category_productkeluar_product_keluar_id",
				Columns:    []*schema.Column{CategoryProductkeluarColumns[1]},
				RefColumns: []*schema.Column{ProductKeluarsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProductCategoryColumns holds the columns for the "product_category" table.
	ProductCategoryColumns = []*schema.Column{
		{Name: "product_id", Type: field.TypeInt},
		{Name: "category_id", Type: field.TypeInt},
	}
	// ProductCategoryTable holds the schema information for the "product_category" table.
	ProductCategoryTable = &schema.Table{
		Name:       "product_category",
		Columns:    ProductCategoryColumns,
		PrimaryKey: []*schema.Column{ProductCategoryColumns[0], ProductCategoryColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_category_product_id",
				Columns:    []*schema.Column{ProductCategoryColumns[0]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_category_category_id",
				Columns:    []*schema.Column{ProductCategoryColumns[1]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProductProductkeluarColumns holds the columns for the "product_productkeluar" table.
	ProductProductkeluarColumns = []*schema.Column{
		{Name: "product_id", Type: field.TypeInt},
		{Name: "product_keluar_id", Type: field.TypeInt},
	}
	// ProductProductkeluarTable holds the schema information for the "product_productkeluar" table.
	ProductProductkeluarTable = &schema.Table{
		Name:       "product_productkeluar",
		Columns:    ProductProductkeluarColumns,
		PrimaryKey: []*schema.Column{ProductProductkeluarColumns[0], ProductProductkeluarColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_productkeluar_product_id",
				Columns:    []*schema.Column{ProductProductkeluarColumns[0]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_productkeluar_product_keluar_id",
				Columns:    []*schema.Column{ProductProductkeluarColumns[1]},
				RefColumns: []*schema.Column{ProductKeluarsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProductProductmasukColumns holds the columns for the "product_productmasuk" table.
	ProductProductmasukColumns = []*schema.Column{
		{Name: "product_id", Type: field.TypeInt},
		{Name: "product_masuk_id", Type: field.TypeInt},
	}
	// ProductProductmasukTable holds the schema information for the "product_productmasuk" table.
	ProductProductmasukTable = &schema.Table{
		Name:       "product_productmasuk",
		Columns:    ProductProductmasukColumns,
		PrimaryKey: []*schema.Column{ProductProductmasukColumns[0], ProductProductmasukColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_productmasuk_product_id",
				Columns:    []*schema.Column{ProductProductmasukColumns[0]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_productmasuk_product_masuk_id",
				Columns:    []*schema.Column{ProductProductmasukColumns[1]},
				RefColumns: []*schema.Column{ProductMasuksColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ProductMasukSupplierColumns holds the columns for the "product_masuk_supplier" table.
	ProductMasukSupplierColumns = []*schema.Column{
		{Name: "product_masuk_id", Type: field.TypeInt},
		{Name: "supplier_id", Type: field.TypeInt},
	}
	// ProductMasukSupplierTable holds the schema information for the "product_masuk_supplier" table.
	ProductMasukSupplierTable = &schema.Table{
		Name:       "product_masuk_supplier",
		Columns:    ProductMasukSupplierColumns,
		PrimaryKey: []*schema.Column{ProductMasukSupplierColumns[0], ProductMasukSupplierColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "product_masuk_supplier_product_masuk_id",
				Columns:    []*schema.Column{ProductMasukSupplierColumns[0]},
				RefColumns: []*schema.Column{ProductMasuksColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "product_masuk_supplier_supplier_id",
				Columns:    []*schema.Column{ProductMasukSupplierColumns[1]},
				RefColumns: []*schema.Column{SuppliersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CategoriesTable,
		CustomersTable,
		ProductsTable,
		ProductKeluarsTable,
		ProductMasuksTable,
		SuppliersTable,
		UsersTable,
		CategoryProductkeluarTable,
		ProductCategoryTable,
		ProductProductkeluarTable,
		ProductProductmasukTable,
		ProductMasukSupplierTable,
	}
)

func init() {
	CategoryProductkeluarTable.ForeignKeys[0].RefTable = CategoriesTable
	CategoryProductkeluarTable.ForeignKeys[1].RefTable = ProductKeluarsTable
	ProductCategoryTable.ForeignKeys[0].RefTable = ProductsTable
	ProductCategoryTable.ForeignKeys[1].RefTable = CategoriesTable
	ProductProductkeluarTable.ForeignKeys[0].RefTable = ProductsTable
	ProductProductkeluarTable.ForeignKeys[1].RefTable = ProductKeluarsTable
	ProductProductmasukTable.ForeignKeys[0].RefTable = ProductsTable
	ProductProductmasukTable.ForeignKeys[1].RefTable = ProductMasuksTable
	ProductMasukSupplierTable.ForeignKeys[0].RefTable = ProductMasuksTable
	ProductMasukSupplierTable.ForeignKeys[1].RefTable = SuppliersTable
}
