// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/inventorygoent/pkg/database/postgres/ent/product"
	"github.com/renaldyhidayatt/inventorygoent/pkg/database/postgres/ent/productmasuk"
	"github.com/renaldyhidayatt/inventorygoent/pkg/database/postgres/ent/supplier"
)

// ProductMasukCreate is the builder for creating a ProductMasuk entity.
type ProductMasukCreate struct {
	config
	mutation *ProductMasukMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pmc *ProductMasukCreate) SetName(s string) *ProductMasukCreate {
	pmc.mutation.SetName(s)
	return pmc
}

// SetQty sets the "qty" field.
func (pmc *ProductMasukCreate) SetQty(s string) *ProductMasukCreate {
	pmc.mutation.SetQty(s)
	return pmc
}

// SetCreatedAt sets the "created_at" field.
func (pmc *ProductMasukCreate) SetCreatedAt(t time.Time) *ProductMasukCreate {
	pmc.mutation.SetCreatedAt(t)
	return pmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pmc *ProductMasukCreate) SetNillableCreatedAt(t *time.Time) *ProductMasukCreate {
	if t != nil {
		pmc.SetCreatedAt(*t)
	}
	return pmc
}

// SetUpdatedAt sets the "updated_at" field.
func (pmc *ProductMasukCreate) SetUpdatedAt(t time.Time) *ProductMasukCreate {
	pmc.mutation.SetUpdatedAt(t)
	return pmc
}

// AddProductIDs adds the "product" edge to the Product entity by IDs.
func (pmc *ProductMasukCreate) AddProductIDs(ids ...int) *ProductMasukCreate {
	pmc.mutation.AddProductIDs(ids...)
	return pmc
}

// AddProduct adds the "product" edges to the Product entity.
func (pmc *ProductMasukCreate) AddProduct(p ...*Product) *ProductMasukCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pmc.AddProductIDs(ids...)
}

// AddSupplierIDs adds the "supplier" edge to the Supplier entity by IDs.
func (pmc *ProductMasukCreate) AddSupplierIDs(ids ...int) *ProductMasukCreate {
	pmc.mutation.AddSupplierIDs(ids...)
	return pmc
}

// AddSupplier adds the "supplier" edges to the Supplier entity.
func (pmc *ProductMasukCreate) AddSupplier(s ...*Supplier) *ProductMasukCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return pmc.AddSupplierIDs(ids...)
}

// Mutation returns the ProductMasukMutation object of the builder.
func (pmc *ProductMasukCreate) Mutation() *ProductMasukMutation {
	return pmc.mutation
}

// Save creates the ProductMasuk in the database.
func (pmc *ProductMasukCreate) Save(ctx context.Context) (*ProductMasuk, error) {
	pmc.defaults()
	return withHooks[*ProductMasuk, ProductMasukMutation](ctx, pmc.sqlSave, pmc.mutation, pmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pmc *ProductMasukCreate) SaveX(ctx context.Context) *ProductMasuk {
	v, err := pmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pmc *ProductMasukCreate) Exec(ctx context.Context) error {
	_, err := pmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmc *ProductMasukCreate) ExecX(ctx context.Context) {
	if err := pmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pmc *ProductMasukCreate) defaults() {
	if _, ok := pmc.mutation.CreatedAt(); !ok {
		v := productmasuk.DefaultCreatedAt()
		pmc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pmc *ProductMasukCreate) check() error {
	if _, ok := pmc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ProductMasuk.name"`)}
	}
	if _, ok := pmc.mutation.Qty(); !ok {
		return &ValidationError{Name: "qty", err: errors.New(`ent: missing required field "ProductMasuk.qty"`)}
	}
	if _, ok := pmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProductMasuk.created_at"`)}
	}
	if _, ok := pmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProductMasuk.updated_at"`)}
	}
	return nil
}

func (pmc *ProductMasukCreate) sqlSave(ctx context.Context) (*ProductMasuk, error) {
	if err := pmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pmc.mutation.id = &_node.ID
	pmc.mutation.done = true
	return _node, nil
}

func (pmc *ProductMasukCreate) createSpec() (*ProductMasuk, *sqlgraph.CreateSpec) {
	var (
		_node = &ProductMasuk{config: pmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: productmasuk.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: productmasuk.FieldID,
			},
		}
	)
	if value, ok := pmc.mutation.Name(); ok {
		_spec.SetField(productmasuk.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pmc.mutation.Qty(); ok {
		_spec.SetField(productmasuk.FieldQty, field.TypeString, value)
		_node.Qty = value
	}
	if value, ok := pmc.mutation.CreatedAt(); ok {
		_spec.SetField(productmasuk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := pmc.mutation.UpdatedAt(); ok {
		_spec.SetField(productmasuk.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := pmc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   productmasuk.ProductTable,
			Columns: productmasuk.ProductPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pmc.mutation.SupplierIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   productmasuk.SupplierTable,
			Columns: productmasuk.SupplierPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: supplier.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProductMasukCreateBulk is the builder for creating many ProductMasuk entities in bulk.
type ProductMasukCreateBulk struct {
	config
	builders []*ProductMasukCreate
}

// Save creates the ProductMasuk entities in the database.
func (pmcb *ProductMasukCreateBulk) Save(ctx context.Context) ([]*ProductMasuk, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pmcb.builders))
	nodes := make([]*ProductMasuk, len(pmcb.builders))
	mutators := make([]Mutator, len(pmcb.builders))
	for i := range pmcb.builders {
		func(i int, root context.Context) {
			builder := pmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProductMasukMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pmcb *ProductMasukCreateBulk) SaveX(ctx context.Context) []*ProductMasuk {
	v, err := pmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pmcb *ProductMasukCreateBulk) Exec(ctx context.Context) error {
	_, err := pmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmcb *ProductMasukCreateBulk) ExecX(ctx context.Context) {
	if err := pmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
