// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/inventorygoent/pkg/database/postgres/ent/productmasuk"
	"github.com/renaldyhidayatt/inventorygoent/pkg/database/postgres/ent/supplier"
)

// SupplierCreate is the builder for creating a Supplier entity.
type SupplierCreate struct {
	config
	mutation *SupplierMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (sc *SupplierCreate) SetName(s string) *SupplierCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetAlamat sets the "alamat" field.
func (sc *SupplierCreate) SetAlamat(s string) *SupplierCreate {
	sc.mutation.SetAlamat(s)
	return sc
}

// SetTelepon sets the "telepon" field.
func (sc *SupplierCreate) SetTelepon(s string) *SupplierCreate {
	sc.mutation.SetTelepon(s)
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SupplierCreate) SetCreatedAt(t time.Time) *SupplierCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SupplierCreate) SetNillableCreatedAt(t *time.Time) *SupplierCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SupplierCreate) SetUpdatedAt(t time.Time) *SupplierCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// AddProductmasukIDs adds the "productmasuk" edge to the ProductMasuk entity by IDs.
func (sc *SupplierCreate) AddProductmasukIDs(ids ...int) *SupplierCreate {
	sc.mutation.AddProductmasukIDs(ids...)
	return sc
}

// AddProductmasuk adds the "productmasuk" edges to the ProductMasuk entity.
func (sc *SupplierCreate) AddProductmasuk(p ...*ProductMasuk) *SupplierCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddProductmasukIDs(ids...)
}

// Mutation returns the SupplierMutation object of the builder.
func (sc *SupplierCreate) Mutation() *SupplierMutation {
	return sc.mutation
}

// Save creates the Supplier in the database.
func (sc *SupplierCreate) Save(ctx context.Context) (*Supplier, error) {
	sc.defaults()
	return withHooks[*Supplier, SupplierMutation](ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SupplierCreate) SaveX(ctx context.Context) *Supplier {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SupplierCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SupplierCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SupplierCreate) defaults() {
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := supplier.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SupplierCreate) check() error {
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Supplier.name"`)}
	}
	if _, ok := sc.mutation.Alamat(); !ok {
		return &ValidationError{Name: "alamat", err: errors.New(`ent: missing required field "Supplier.alamat"`)}
	}
	if _, ok := sc.mutation.Telepon(); !ok {
		return &ValidationError{Name: "telepon", err: errors.New(`ent: missing required field "Supplier.telepon"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Supplier.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Supplier.updated_at"`)}
	}
	return nil
}

func (sc *SupplierCreate) sqlSave(ctx context.Context) (*Supplier, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SupplierCreate) createSpec() (*Supplier, *sqlgraph.CreateSpec) {
	var (
		_node = &Supplier{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: supplier.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplier.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(supplier.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Alamat(); ok {
		_spec.SetField(supplier.FieldAlamat, field.TypeString, value)
		_node.Alamat = value
	}
	if value, ok := sc.mutation.Telepon(); ok {
		_spec.SetField(supplier.FieldTelepon, field.TypeString, value)
		_node.Telepon = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(supplier.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(supplier.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sc.mutation.ProductmasukIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   supplier.ProductmasukTable,
			Columns: supplier.ProductmasukPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: productmasuk.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SupplierCreateBulk is the builder for creating many Supplier entities in bulk.
type SupplierCreateBulk struct {
	config
	builders []*SupplierCreate
}

// Save creates the Supplier entities in the database.
func (scb *SupplierCreateBulk) Save(ctx context.Context) ([]*Supplier, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Supplier, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SupplierCreateBulk) SaveX(ctx context.Context) []*Supplier {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SupplierCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SupplierCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
