// Code generated by ent, DO NOT EDIT.

package productmasuk

import (
	"time"
)

const (
	// Label holds the string label denoting the productmasuk type in the database.
	Label = "product_masuk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldQty holds the string denoting the qty field in the database.
	FieldQty = "qty"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeSupplier holds the string denoting the supplier edge name in mutations.
	EdgeSupplier = "supplier"
	// Table holds the table name of the productmasuk in the database.
	Table = "product_masuks"
	// ProductTable is the table that holds the product relation/edge. The primary key declared below.
	ProductTable = "product_productmasuk"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// SupplierTable is the table that holds the supplier relation/edge. The primary key declared below.
	SupplierTable = "product_masuk_supplier"
	// SupplierInverseTable is the table name for the Supplier entity.
	// It exists in this package in order to avoid circular dependency with the "supplier" package.
	SupplierInverseTable = "suppliers"
)

// Columns holds all SQL columns for productmasuk fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldQty,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// ProductPrimaryKey and ProductColumn2 are the table columns denoting the
	// primary key for the product relation (M2M).
	ProductPrimaryKey = []string{"product_id", "product_masuk_id"}
	// SupplierPrimaryKey and SupplierColumn2 are the table columns denoting the
	// primary key for the supplier relation (M2M).
	SupplierPrimaryKey = []string{"product_masuk_id", "supplier_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
