// Code generated by ent, DO NOT EDIT.

package product

import (
	"time"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldQty holds the string denoting the qty field in the database.
	FieldQty = "qty"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCategory holds the string denoting the category edge name in mutations.
	EdgeCategory = "category"
	// EdgeProductkeluar holds the string denoting the productkeluar edge name in mutations.
	EdgeProductkeluar = "productkeluar"
	// EdgeProductmasuk holds the string denoting the productmasuk edge name in mutations.
	EdgeProductmasuk = "productmasuk"
	// Table holds the table name of the product in the database.
	Table = "products"
	// CategoryTable is the table that holds the category relation/edge. The primary key declared below.
	CategoryTable = "product_category"
	// CategoryInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoryInverseTable = "categories"
	// ProductkeluarTable is the table that holds the productkeluar relation/edge. The primary key declared below.
	ProductkeluarTable = "product_productkeluar"
	// ProductkeluarInverseTable is the table name for the ProductKeluar entity.
	// It exists in this package in order to avoid circular dependency with the "productkeluar" package.
	ProductkeluarInverseTable = "product_keluars"
	// ProductmasukTable is the table that holds the productmasuk relation/edge. The primary key declared below.
	ProductmasukTable = "product_productmasuk"
	// ProductmasukInverseTable is the table name for the ProductMasuk entity.
	// It exists in this package in order to avoid circular dependency with the "productmasuk" package.
	ProductmasukInverseTable = "product_masuks"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldImage,
	FieldQty,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// CategoryPrimaryKey and CategoryColumn2 are the table columns denoting the
	// primary key for the category relation (M2M).
	CategoryPrimaryKey = []string{"product_id", "category_id"}
	// ProductkeluarPrimaryKey and ProductkeluarColumn2 are the table columns denoting the
	// primary key for the productkeluar relation (M2M).
	ProductkeluarPrimaryKey = []string{"product_id", "product_keluar_id"}
	// ProductmasukPrimaryKey and ProductmasukColumn2 are the table columns denoting the
	// primary key for the productmasuk relation (M2M).
	ProductmasukPrimaryKey = []string{"product_id", "product_masuk_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
