// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/inventorygoent/ent/predicate"
	"github.com/renaldyhidayatt/inventorygoent/ent/productmasuk"
)

// ProductMasukDelete is the builder for deleting a ProductMasuk entity.
type ProductMasukDelete struct {
	config
	hooks    []Hook
	mutation *ProductMasukMutation
}

// Where appends a list predicates to the ProductMasukDelete builder.
func (pmd *ProductMasukDelete) Where(ps ...predicate.ProductMasuk) *ProductMasukDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *ProductMasukDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, ProductMasukMutation](ctx, pmd.sqlExec, pmd.mutation, pmd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *ProductMasukDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *ProductMasukDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: productmasuk.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: productmasuk.FieldID,
			},
		},
	}
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pmd.mutation.done = true
	return affected, err
}

// ProductMasukDeleteOne is the builder for deleting a single ProductMasuk entity.
type ProductMasukDeleteOne struct {
	pmd *ProductMasukDelete
}

// Where appends a list predicates to the ProductMasukDelete builder.
func (pmdo *ProductMasukDeleteOne) Where(ps ...predicate.ProductMasuk) *ProductMasukDeleteOne {
	pmdo.pmd.mutation.Where(ps...)
	return pmdo
}

// Exec executes the deletion query.
func (pmdo *ProductMasukDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{productmasuk.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *ProductMasukDeleteOne) ExecX(ctx context.Context) {
	if err := pmdo.Exec(ctx); err != nil {
		panic(err)
	}
}
