// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/renaldyhidayatt/inventorygoent/ent/category"
	"github.com/renaldyhidayatt/inventorygoent/ent/customer"
	"github.com/renaldyhidayatt/inventorygoent/ent/product"
	"github.com/renaldyhidayatt/inventorygoent/ent/productkeluar"
	"github.com/renaldyhidayatt/inventorygoent/ent/productmasuk"
	"github.com/renaldyhidayatt/inventorygoent/ent/schema"
	"github.com/renaldyhidayatt/inventorygoent/ent/supplier"
	"github.com/renaldyhidayatt/inventorygoent/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	categoryFields := schema.Category{}.Fields()
	_ = categoryFields
	// categoryDescCreatedAt is the schema descriptor for created_at field.
	categoryDescCreatedAt := categoryFields[1].Descriptor()
	// category.DefaultCreatedAt holds the default value on creation for the created_at field.
	category.DefaultCreatedAt = categoryDescCreatedAt.Default.(func() time.Time)
	// categoryDescUpdatedAt is the schema descriptor for updated_at field.
	categoryDescUpdatedAt := categoryFields[2].Descriptor()
	// category.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	category.UpdateDefaultUpdatedAt = categoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	customerFields := schema.Customer{}.Fields()
	_ = customerFields
	// customerDescCreatedAt is the schema descriptor for created_at field.
	customerDescCreatedAt := customerFields[3].Descriptor()
	// customer.DefaultCreatedAt holds the default value on creation for the created_at field.
	customer.DefaultCreatedAt = customerDescCreatedAt.Default.(func() time.Time)
	// customerDescUpdatedAt is the schema descriptor for updated_at field.
	customerDescUpdatedAt := customerFields[4].Descriptor()
	// customer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	customer.UpdateDefaultUpdatedAt = customerDescUpdatedAt.UpdateDefault.(func() time.Time)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[3].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	// productDescUpdatedAt is the schema descriptor for updated_at field.
	productDescUpdatedAt := productFields[4].Descriptor()
	// product.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	product.UpdateDefaultUpdatedAt = productDescUpdatedAt.UpdateDefault.(func() time.Time)
	productkeluarFields := schema.ProductKeluar{}.Fields()
	_ = productkeluarFields
	// productkeluarDescCreatedAt is the schema descriptor for created_at field.
	productkeluarDescCreatedAt := productkeluarFields[1].Descriptor()
	// productkeluar.DefaultCreatedAt holds the default value on creation for the created_at field.
	productkeluar.DefaultCreatedAt = productkeluarDescCreatedAt.Default.(func() time.Time)
	// productkeluarDescUpdatedAt is the schema descriptor for updated_at field.
	productkeluarDescUpdatedAt := productkeluarFields[2].Descriptor()
	// productkeluar.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productkeluar.UpdateDefaultUpdatedAt = productkeluarDescUpdatedAt.UpdateDefault.(func() time.Time)
	productmasukFields := schema.ProductMasuk{}.Fields()
	_ = productmasukFields
	// productmasukDescCreatedAt is the schema descriptor for created_at field.
	productmasukDescCreatedAt := productmasukFields[2].Descriptor()
	// productmasuk.DefaultCreatedAt holds the default value on creation for the created_at field.
	productmasuk.DefaultCreatedAt = productmasukDescCreatedAt.Default.(func() time.Time)
	// productmasukDescUpdatedAt is the schema descriptor for updated_at field.
	productmasukDescUpdatedAt := productmasukFields[3].Descriptor()
	// productmasuk.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	productmasuk.UpdateDefaultUpdatedAt = productmasukDescUpdatedAt.UpdateDefault.(func() time.Time)
	supplierFields := schema.Supplier{}.Fields()
	_ = supplierFields
	// supplierDescCreatedAt is the schema descriptor for created_at field.
	supplierDescCreatedAt := supplierFields[3].Descriptor()
	// supplier.DefaultCreatedAt holds the default value on creation for the created_at field.
	supplier.DefaultCreatedAt = supplierDescCreatedAt.Default.(func() time.Time)
	// supplierDescUpdatedAt is the schema descriptor for updated_at field.
	supplierDescUpdatedAt := supplierFields[4].Descriptor()
	// supplier.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	supplier.UpdateDefaultUpdatedAt = supplierDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
