// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/renaldyhidayatt/inventorygoent/ent/predicate"
	"github.com/renaldyhidayatt/inventorygoent/ent/productmasuk"
	"github.com/renaldyhidayatt/inventorygoent/ent/supplier"
)

// SupplierQuery is the builder for querying Supplier entities.
type SupplierQuery struct {
	config
	ctx              *QueryContext
	order            []OrderFunc
	inters           []Interceptor
	predicates       []predicate.Supplier
	withProductmasuk *ProductMasukQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SupplierQuery builder.
func (sq *SupplierQuery) Where(ps ...predicate.Supplier) *SupplierQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *SupplierQuery) Limit(limit int) *SupplierQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *SupplierQuery) Offset(offset int) *SupplierQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *SupplierQuery) Unique(unique bool) *SupplierQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *SupplierQuery) Order(o ...OrderFunc) *SupplierQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryProductmasuk chains the current query on the "productmasuk" edge.
func (sq *SupplierQuery) QueryProductmasuk() *ProductMasukQuery {
	query := (&ProductMasukClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(supplier.Table, supplier.FieldID, selector),
			sqlgraph.To(productmasuk.Table, productmasuk.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, supplier.ProductmasukTable, supplier.ProductmasukPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Supplier entity from the query.
// Returns a *NotFoundError when no Supplier was found.
func (sq *SupplierQuery) First(ctx context.Context) (*Supplier, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{supplier.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *SupplierQuery) FirstX(ctx context.Context) *Supplier {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Supplier ID from the query.
// Returns a *NotFoundError when no Supplier ID was found.
func (sq *SupplierQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{supplier.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *SupplierQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Supplier entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Supplier entity is found.
// Returns a *NotFoundError when no Supplier entities are found.
func (sq *SupplierQuery) Only(ctx context.Context) (*Supplier, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{supplier.Label}
	default:
		return nil, &NotSingularError{supplier.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *SupplierQuery) OnlyX(ctx context.Context) *Supplier {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Supplier ID in the query.
// Returns a *NotSingularError when more than one Supplier ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *SupplierQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{supplier.Label}
	default:
		err = &NotSingularError{supplier.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *SupplierQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Suppliers.
func (sq *SupplierQuery) All(ctx context.Context) ([]*Supplier, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Supplier, *SupplierQuery]()
	return withInterceptors[[]*Supplier](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *SupplierQuery) AllX(ctx context.Context) []*Supplier {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Supplier IDs.
func (sq *SupplierQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err := sq.Select(supplier.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *SupplierQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *SupplierQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*SupplierQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *SupplierQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *SupplierQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *SupplierQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SupplierQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *SupplierQuery) Clone() *SupplierQuery {
	if sq == nil {
		return nil
	}
	return &SupplierQuery{
		config:           sq.config,
		ctx:              sq.ctx.Clone(),
		order:            append([]OrderFunc{}, sq.order...),
		inters:           append([]Interceptor{}, sq.inters...),
		predicates:       append([]predicate.Supplier{}, sq.predicates...),
		withProductmasuk: sq.withProductmasuk.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithProductmasuk tells the query-builder to eager-load the nodes that are connected to
// the "productmasuk" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *SupplierQuery) WithProductmasuk(opts ...func(*ProductMasukQuery)) *SupplierQuery {
	query := (&ProductMasukClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withProductmasuk = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Supplier.Query().
//		GroupBy(supplier.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *SupplierQuery) GroupBy(field string, fields ...string) *SupplierGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SupplierGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = supplier.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Supplier.Query().
//		Select(supplier.FieldName).
//		Scan(ctx, &v)
func (sq *SupplierQuery) Select(fields ...string) *SupplierSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &SupplierSelect{SupplierQuery: sq}
	sbuild.label = supplier.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SupplierSelect configured with the given aggregations.
func (sq *SupplierQuery) Aggregate(fns ...AggregateFunc) *SupplierSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *SupplierQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !supplier.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *SupplierQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Supplier, error) {
	var (
		nodes       = []*Supplier{}
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withProductmasuk != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Supplier).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Supplier{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withProductmasuk; query != nil {
		if err := sq.loadProductmasuk(ctx, query, nodes,
			func(n *Supplier) { n.Edges.Productmasuk = []*ProductMasuk{} },
			func(n *Supplier, e *ProductMasuk) { n.Edges.Productmasuk = append(n.Edges.Productmasuk, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *SupplierQuery) loadProductmasuk(ctx context.Context, query *ProductMasukQuery, nodes []*Supplier, init func(*Supplier), assign func(*Supplier, *ProductMasuk)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Supplier)
	nids := make(map[int]map[*Supplier]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(supplier.ProductmasukTable)
		s.Join(joinT).On(s.C(productmasuk.FieldID), joinT.C(supplier.ProductmasukPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(supplier.ProductmasukPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(supplier.ProductmasukPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Supplier]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*ProductMasuk](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "productmasuk" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (sq *SupplierQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *SupplierQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   supplier.Table,
			Columns: supplier.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: supplier.FieldID,
			},
		},
		From:   sq.sql,
		Unique: true,
	}
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplier.FieldID)
		for i := range fields {
			if fields[i] != supplier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *SupplierQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(supplier.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = supplier.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SupplierGroupBy is the group-by builder for Supplier entities.
type SupplierGroupBy struct {
	selector
	build *SupplierQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *SupplierGroupBy) Aggregate(fns ...AggregateFunc) *SupplierGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *SupplierGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupplierQuery, *SupplierGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *SupplierGroupBy) sqlScan(ctx context.Context, root *SupplierQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SupplierSelect is the builder for selecting fields of Supplier entities.
type SupplierSelect struct {
	*SupplierQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *SupplierSelect) Aggregate(fns ...AggregateFunc) *SupplierSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *SupplierSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SupplierQuery, *SupplierSelect](ctx, ss.SupplierQuery, ss, ss.inters, v)
}

func (ss *SupplierSelect) sqlScan(ctx context.Context, root *SupplierQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
