// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductKeluar is the predicate function for productkeluar builders.
type ProductKeluar func(*sql.Selector)

// ProductMasuk is the predicate function for productmasuk builders.
type ProductMasuk func(*sql.Selector)

// Supplier is the predicate function for supplier builders.
type Supplier func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
